from datetime import date

from sqlalchemy import select
from sqlalchemy.orm import Session

from app.database import SessionLocal
from app.models import Document, Program, Source

CHECKED = date(2026, 5, 26)

SOURCE_SEEDS = [
    {"name": "Maryland Business Express", "agency": "State of Maryland", "url": "https://businessexpress.maryland.gov/", "jurisdiction": "Maryland", "source_type": "startup", "last_checked_at": CHECKED, "notes": "Business registration and startup checklist hub."},
    {"name": "Maryland Department of Commerce Funding", "agency": "Maryland Department of Commerce", "url": "https://commerce.maryland.gov/fund", "jurisdiction": "Maryland", "source_type": "funding", "last_checked_at": CHECKED, "notes": "State business funding and incentive overview."},
    {"name": "Maryland eMMA", "agency": "Maryland Procurement", "url": "https://emma.maryland.gov/", "jurisdiction": "Maryland", "source_type": "procurement", "last_checked_at": CHECKED, "notes": "Maryland vendor registration and procurement portal."},
    {"name": "SAM.gov Entity Registration", "agency": "U.S. General Services Administration", "url": "https://sam.gov/content/entity-registration", "jurisdiction": "Federal", "source_type": "procurement", "last_checked_at": CHECKED, "notes": "Federal entity registration and UEI."},
    {"name": "IRS W-9", "agency": "Internal Revenue Service", "url": "https://www.irs.gov/forms-pubs/about-form-w-9", "jurisdiction": "Federal", "source_type": "tax", "last_checked_at": CHECKED, "notes": "Official W-9 form page."},
    {"name": "SBA Microloans", "agency": "U.S. Small Business Administration", "url": "https://www.sba.gov/funding-programs/loans/microloans", "jurisdiction": "Federal", "source_type": "loan", "last_checked_at": CHECKED, "notes": "SBA microloan program information."},
    {"name": "Maryland Energy Administration", "agency": "Maryland Energy Administration", "url": "https://energy.maryland.gov/", "jurisdiction": "Maryland", "source_type": "energy", "last_checked_at": CHECKED, "notes": "Energy grants and incentive source."},
    {"name": "Maryland Workforce Development", "agency": "Maryland Department of Labor", "url": "https://www.labor.maryland.gov/employment/", "jurisdiction": "Maryland", "source_type": "workforce", "last_checked_at": CHECKED, "notes": "Workforce and training programs."},
    {"name": "County Economic Development Sample Source", "agency": "Maryland Counties", "url": "https://commerce.maryland.gov/about/regional-resources", "jurisdiction": "County", "source_type": "county", "last_checked_at": CHECKED, "notes": "County economic development routing source for MVP sample data."},
    {"name": "Maryland Certification Programs", "agency": "Maryland Department of Transportation", "url": "https://www.mdot.maryland.gov/tso/pages/Index.aspx?PageId=90", "jurisdiction": "Maryland", "source_type": "certification", "last_checked_at": CHECKED, "notes": "MBE, DBE, and SBE certification information."},
]

PROGRAM_SEEDS = [
    {"name": "Maryland Business Express Startup Checklist", "source_name": "Maryland Business Express", "funding_type": "readiness", "category": "startup capital", "best_fit": "New Maryland businesses that need registration steps before seeking funding.", "eligibility_summary": "May fit Maryland founders who need to register, choose an entity type, and prepare basic records.", "required_documents": ["Business name", "Entity type", "Owner information"], "difficulty": "easy", "estimated_time": "1-2 hours", "official_url": "https://businessexpress.maryland.gov/", "last_checked_at": CHECKED, "confidence": "high", "next_action": "Review the startup checklist and confirm your business registration status."},
    {"name": "Maryland Commerce Funding and Incentives", "source_name": "Maryland Department of Commerce Funding", "funding_type": "grant or incentive", "category": "working capital", "best_fit": "Maryland businesses exploring state funding, loans, or incentives.", "eligibility_summary": "May qualify depending on business size, location, hiring, investment, and program rules.", "required_documents": ["Business plan", "Financials", "Maryland registration"], "difficulty": "medium", "estimated_time": "2-6 hours", "official_url": "https://commerce.maryland.gov/fund", "last_checked_at": CHECKED, "confidence": "medium", "next_action": "Open the official Commerce funding page and identify programs matching your stage."},
    {"name": "Maryland Small Business Development Financing Authority", "source_name": "Maryland Department of Commerce Funding", "funding_type": "loan", "category": "working capital", "best_fit": "Small businesses that may need credit support or financing assistance.", "eligibility_summary": "May fit Maryland businesses that cannot obtain reasonable financing on conventional terms.", "required_documents": ["Business financials", "Use of funds", "Owner information"], "difficulty": "hard", "estimated_time": "1-3 weeks", "official_url": "https://commerce.maryland.gov/fund/programs-for-businesses/msbdfa", "last_checked_at": CHECKED, "confidence": "medium", "next_action": "Review MSBDFA requirements and talk with a lender or Maryland Commerce representative."},
    {"name": "eMMA Vendor Registration", "source_name": "Maryland eMMA", "funding_type": "procurement", "category": "government contracting", "best_fit": "Businesses interested in Maryland state contracting opportunities.", "eligibility_summary": "Likely relevant if you want to bid on Maryland procurement opportunities.", "required_documents": ["Business information", "Tax ID", "Commodity codes"], "difficulty": "medium", "estimated_time": "1-3 hours", "official_url": "https://emma.maryland.gov/", "last_checked_at": CHECKED, "confidence": "high", "next_action": "Create or update your eMMA vendor account."},
    {"name": "SAM.gov Entity Registration", "source_name": "SAM.gov Entity Registration", "funding_type": "procurement", "category": "government contracting", "best_fit": "Businesses preparing for federal contracts or grants.", "eligibility_summary": "Likely relevant if you want federal awards, contracts, or certain grant opportunities.", "required_documents": ["EIN", "Legal business name", "Banking information", "NAICS codes"], "difficulty": "hard", "estimated_time": "1-2 weeks", "official_url": "https://sam.gov/content/entity-registration", "last_checked_at": CHECKED, "confidence": "high", "next_action": "Start SAM.gov registration and gather legal entity details before submitting."},
    {"name": "IRS W-9", "source_name": "IRS W-9", "funding_type": "paperwork", "category": "tax", "best_fit": "Businesses that need to provide taxpayer information to customers, agencies, or primes.", "eligibility_summary": "Relevant for most U.S. businesses receiving reportable payments.", "required_documents": ["Legal name", "Tax classification", "TIN or EIN"], "difficulty": "easy", "estimated_time": "15-30 minutes", "official_url": "https://www.irs.gov/forms-pubs/about-form-w-9", "last_checked_at": CHECKED, "confidence": "high", "next_action": "Download the official W-9 and prepare your taxpayer information."},
    {"name": "SBA Microloan", "source_name": "SBA Microloans", "funding_type": "loan", "category": "startup capital", "best_fit": "Startups and small businesses seeking smaller loan amounts through intermediaries.", "eligibility_summary": "May qualify through an SBA-approved intermediary depending on credit, use of funds, and business plan.", "required_documents": ["Business plan", "Financial projections", "Use of funds"], "difficulty": "medium", "estimated_time": "1-4 weeks", "official_url": "https://www.sba.gov/funding-programs/loans/microloans", "last_checked_at": CHECKED, "confidence": "medium", "next_action": "Find an SBA microloan intermediary serving Maryland."},
    {"name": "Workforce Training Grant Category", "source_name": "Maryland Workforce Development", "funding_type": "grant", "category": "training", "best_fit": "Businesses planning to hire or train workers.", "eligibility_summary": "May qualify if training aligns with workforce program rules and funding availability.", "required_documents": ["Training plan", "Employee count", "Wage information"], "difficulty": "medium", "estimated_time": "2-6 hours", "official_url": "https://www.labor.maryland.gov/employment/", "last_checked_at": CHECKED, "confidence": "needs review", "next_action": "Review Maryland workforce program options and contact a local workforce board."},
    {"name": "Utility Rebate Category", "source_name": "Maryland Energy Administration", "funding_type": "rebate", "category": "energy savings", "best_fit": "Businesses considering energy efficiency upgrades.", "eligibility_summary": "May qualify through utility or state energy programs depending on equipment and location.", "required_documents": ["Utility account", "Equipment details", "Contractor estimate"], "difficulty": "medium", "estimated_time": "1-4 hours", "official_url": "https://energy.maryland.gov/", "last_checked_at": CHECKED, "confidence": "needs review", "next_action": "Check utility and Maryland Energy Administration incentives before buying equipment."},
    {"name": "County Economic Development Sample Program", "source_name": "County Economic Development Sample Source", "funding_type": "local program", "category": "working capital", "best_fit": "Businesses that should check county-level incentives and support.", "eligibility_summary": "Needs review because county programs vary by location, industry, and funding cycle.", "required_documents": ["County location", "Business registration", "Use of funds"], "difficulty": "medium", "estimated_time": "1-3 hours", "official_url": "https://commerce.maryland.gov/about/regional-resources", "last_checked_at": CHECKED, "confidence": "needs review", "next_action": "Contact your county economic development office and ask about current business incentives."},
]

DOCUMENT_SEEDS = [
    {"name": "IRS W-9", "source_name": "IRS W-9", "category": "tax", "summary": "A tax form used to give your taxpayer information to someone who may pay your business.", "who_needs_it": "Most businesses that receive payments from customers, agencies, or prime contractors.", "why_it_matters": "It helps payers report payments correctly and is often requested before contracts or payments.", "required_information": ["Legal name", "Business name", "Tax classification", "Address", "TIN or EIN"], "common_mistakes": ["Using a nickname instead of legal name", "Wrong tax classification", "Missing signature"], "official_url": "https://www.irs.gov/forms-pubs/about-form-w-9", "steps": ["Download the official W-9.", "Enter legal taxpayer information.", "Confirm the EIN or SSN is correct.", "Sign and date before sharing securely."]},
    {"name": "EIN", "source_name": "Maryland Business Express", "category": "tax", "summary": "An Employer Identification Number is a federal tax ID for your business.", "who_needs_it": "LLCs, corporations, employers, and many businesses opening bank accounts.", "why_it_matters": "Many funding, banking, tax, and procurement steps ask for an EIN.", "required_information": ["Responsible party", "Legal entity name", "Entity type", "Business address"], "common_mistakes": ["Applying before entity details are final", "Losing the confirmation letter"], "official_url": "https://www.irs.gov/businesses/small-businesses-self-employed/apply-for-an-employer-identification-number-ein-online", "steps": ["Confirm legal entity details.", "Apply through the IRS EIN assistant.", "Save the confirmation letter."]},
    {"name": "Maryland SDAT Registration", "source_name": "Maryland Business Express", "category": "startup", "summary": "Maryland entity registration through the State Department of Assessments and Taxation.", "who_needs_it": "Maryland LLCs, corporations, and other registered entities.", "why_it_matters": "It establishes your entity record in Maryland.", "required_information": ["Entity name", "Resident agent", "Business address", "Organizer information"], "common_mistakes": ["Unavailable business name", "Incorrect resident agent details"], "official_url": "https://businessexpress.maryland.gov/", "steps": ["Search entity name availability.", "Prepare resident agent details.", "File through Maryland Business Express."]},
    {"name": "Maryland Business Express Registration", "source_name": "Maryland Business Express", "category": "startup", "summary": "Maryland's portal for business startup and registration steps.", "who_needs_it": "New Maryland businesses preparing state registration and tax accounts.", "why_it_matters": "It helps route required state startup steps.", "required_information": ["Business name", "Entity type", "Owner details"], "common_mistakes": ["Skipping tax account setup", "Using inconsistent business names"], "official_url": "https://businessexpress.maryland.gov/", "steps": ["Create an account.", "Follow the startup checklist.", "Save confirmation records."]},
    {"name": "SAM.gov Registration", "source_name": "SAM.gov Entity Registration", "category": "procurement", "summary": "Federal entity registration for contracts, grants, and assistance awards.", "who_needs_it": "Businesses pursuing federal contracts or certain grants.", "why_it_matters": "SAM.gov creates or maintains the federal registration tied to your UEI.", "required_information": ["Legal name", "EIN", "Banking details", "NAICS codes"], "common_mistakes": ["Name mismatch", "Expired registration", "Wrong banking details"], "official_url": "https://sam.gov/content/entity-registration", "steps": ["Create a Login.gov account.", "Gather entity records.", "Complete entity registration.", "Monitor validation status."]},
    {"name": "Unique Entity ID / UEI", "source_name": "SAM.gov Entity Registration", "category": "procurement", "summary": "A federal identifier assigned through SAM.gov.", "who_needs_it": "Entities pursuing federal awards or registrations.", "why_it_matters": "It identifies your organization in federal systems.", "required_information": ["Legal entity information", "Physical address"], "common_mistakes": ["Creating duplicate records", "Using old DUNS-only instructions"], "official_url": "https://sam.gov/content/entity-registration", "steps": ["Sign into SAM.gov.", "Request or confirm the UEI.", "Keep the UEI with procurement records."]},
    {"name": "eMMA Vendor Registration", "source_name": "Maryland eMMA", "category": "procurement", "summary": "Maryland's vendor registration for procurement opportunities.", "who_needs_it": "Businesses interested in Maryland state contracting.", "why_it_matters": "It lets vendors find and respond to Maryland solicitations.", "required_information": ["Business details", "Tax ID", "Commodity codes"], "common_mistakes": ["Incomplete commodity codes", "Outdated contact email"], "official_url": "https://emma.maryland.gov/", "steps": ["Create an eMMA account.", "Complete vendor profile.", "Add commodity codes.", "Save login details."]},
    {"name": "Maryland SBR / Small Business Reserve", "source_name": "Maryland eMMA", "category": "certification", "summary": "A Maryland procurement program that reserves some opportunities for small businesses.", "who_needs_it": "Small businesses pursuing Maryland procurement.", "why_it_matters": "It may open access to reserved procurement opportunities.", "required_information": ["Business size details", "Maryland vendor profile"], "common_mistakes": ["Assuming eMMA registration automatically completes SBR", "Missing renewal steps"], "official_url": "https://emma.maryland.gov/", "steps": ["Review SBR eligibility.", "Update vendor profile.", "Complete SBR registration steps."]},
    {"name": "MBE / DBE / SBE Certifications", "source_name": "Maryland Certification Programs", "category": "certification", "summary": "Certification programs for minority, disadvantaged, or small business participation.", "who_needs_it": "Eligible businesses seeking certification-based contracting opportunities.", "why_it_matters": "Certifications may improve access to some procurement opportunities.", "required_information": ["Ownership records", "Control documents", "Business financials"], "common_mistakes": ["Insufficient ownership documentation", "Waiting until a bid is due"], "official_url": "https://www.mdot.maryland.gov/tso/pages/Index.aspx?PageId=90", "steps": ["Review certification types.", "Gather ownership documents.", "Submit the application.", "Respond to follow-up requests."]},
    {"name": "Capability Statement", "source_name": "Maryland eMMA", "category": "procurement", "summary": "A short business resume for agencies and prime contractors.", "who_needs_it": "Businesses pursuing government or prime contractor work.", "why_it_matters": "It quickly explains what you do, differentiators, NAICS codes, and contact details.", "required_information": ["Core competencies", "Past performance", "Differentiators", "NAICS codes"], "common_mistakes": ["Too long", "No clear contact information", "Missing NAICS codes"], "official_url": "https://www.sba.gov/federal-contracting/contracting-guide/prime-subcontracting", "steps": ["List core services.", "Add differentiators.", "Add NAICS and contact details.", "Export as a one-page PDF."]},
    {"name": "Grant Budget Template", "source_name": "Maryland Department of Commerce Funding", "category": "grant", "summary": "A worksheet that explains how requested funds will be used.", "who_needs_it": "Businesses applying for grants or incentives that ask for a budget.", "why_it_matters": "Funders need to see eligible costs and realistic totals.", "required_information": ["Cost categories", "Quotes", "Matching funds", "Timeline"], "common_mistakes": ["Unclear cost categories", "Math errors", "Unsupported estimates"], "official_url": "https://commerce.maryland.gov/fund", "steps": ["List eligible costs.", "Collect quotes.", "Separate requested and matching funds.", "Check totals."]},
    {"name": "Business Personal Property Return", "source_name": "Maryland Business Express", "category": "compliance", "summary": "A Maryland filing about business-owned personal property.", "who_needs_it": "Many Maryland entities with business personal property reporting obligations.", "why_it_matters": "Missing filings can create compliance problems.", "required_information": ["Entity ID", "Business property details", "Depreciation schedules"], "common_mistakes": ["Missing annual deadlines", "Ignoring zero-property requirements"], "official_url": "https://dat.maryland.gov/businesses/Pages/Business-Personal-Property.aspx", "steps": ["Check filing requirement.", "Gather property records.", "File through Maryland systems.", "Save confirmation."]},
    {"name": "NAICS Code Selection", "source_name": "SAM.gov Entity Registration", "category": "procurement", "summary": "Choosing industry codes that describe your business activities.", "who_needs_it": "Businesses registering for procurement, grants, loans, or industry programs.", "why_it_matters": "NAICS codes affect searches, eligibility, and contracting categories.", "required_information": ["Business services", "Revenue lines", "Target opportunities"], "common_mistakes": ["Choosing only one vague code", "Ignoring procurement target codes"], "official_url": "https://www.census.gov/naics/", "steps": ["Search NAICS descriptions.", "Pick primary and secondary codes.", "Use consistent codes across systems."]},
]


def seed_database(db: Session) -> None:
    sources_by_name: dict[str, Source] = {}
    for item in SOURCE_SEEDS:
        source = db.scalar(select(Source).where(Source.name == item["name"])) or Source(name=item["name"])
        for key, value in item.items():
            setattr(source, key, value)
        db.add(source)
        sources_by_name[item["name"]] = source
    db.flush()

    for item in PROGRAM_SEEDS:
        data = item.copy()
        source_name = data.pop("source_name")
        program = db.scalar(select(Program).where(Program.name == data["name"])) or Program(name=data["name"])
        for key, value in data.items():
            setattr(program, key, value)
        program.source_id = sources_by_name[source_name].id
        db.add(program)

    for item in DOCUMENT_SEEDS:
        data = item.copy()
        source_name = data.pop("source_name")
        document = db.scalar(select(Document).where(Document.name == data["name"])) or Document(name=data["name"])
        for key, value in data.items():
            setattr(document, key, value)
        document.source_id = sources_by_name[source_name].id
        db.add(document)

    db.commit()


def main() -> None:
    with SessionLocal() as db:
        seed_database(db)


if __name__ == "__main__":
    main()
